In [4]:
import os
import pandas as pd
import re

In [65]:
df = pd.read_csv('AdventDay2.txt', sep= ':',header=None)
print(df)

           0                                                  1
0     Game 1   1 blue, 1 red; 10 red; 8 red, 1 blue, 1 green...
1     Game 2   9 green, 11 red; 1 green, 7 red, 1 blue; 1 re...
2     Game 3   16 blue, 2 red, 4 green; 8 red, 4 green; 7 gr...
3     Game 4   3 green, 4 blue, 6 red; 7 red, 12 green, 5 bl...
4     Game 5   4 green, 4 blue, 3 red; 4 green, 7 red, 1 blu...
..       ...                                                ...
95   Game 96   5 red, 8 blue, 5 green; 12 blue, 2 red; 15 bl...
96   Game 97   5 red, 5 blue; 1 red, 11 blue; 3 green, 10 bl...
97   Game 98   4 red, 3 blue, 8 green; 5 blue, 2 red, 8 gree...
98   Game 99   7 green, 3 red, 9 blue; 3 blue, 5 red, 4 gree...
99  Game 100   2 blue, 1 red; 4 blue, 2 red, 1 green; 7 red,...

[100 rows x 2 columns]

In [66]:
df = df.set_axis(['Game','Values'], axis=1)
print(df)

        Game                                             Values
0     Game 1   1 blue, 1 red; 10 red; 8 red, 1 blue, 1 green...
1     Game 2   9 green, 11 red; 1 green, 7 red, 1 blue; 1 re...
2     Game 3   16 blue, 2 red, 4 green; 8 red, 4 green; 7 gr...
3     Game 4   3 green, 4 blue, 6 red; 7 red, 12 green, 5 bl...
4     Game 5   4 green, 4 blue, 3 red; 4 green, 7 red, 1 blu...
..       ...                                                ...
95   Game 96   5 red, 8 blue, 5 green; 12 blue, 2 red; 15 bl...
96   Game 97   5 red, 5 blue; 1 red, 11 blue; 3 green, 10 bl...
97   Game 98   4 red, 3 blue, 8 green; 5 blue, 2 red, 8 gree...
98   Game 99   7 green, 3 red, 9 blue; 3 blue, 5 red, 4 gree...
99  Game 100   2 blue, 1 red; 4 blue, 2 red, 1 green; 7 red,...

[100 rows x 2 columns]

In [67]:
df['Game'] =df['Game'].str.replace('[^\d\.]','', regex=True).astype(int)

df['Blue'] = df['Values'].str.findall(r'(\d+) blue')
df['Blue'] = df['Blue'].apply(lambda lst: list(map(int, lst)))
df['red'] = df['Values'].str.findall(r'(\d+) red')
df['red'] = df['red'].apply(lambda lst: list(map(int, lst)))
df['green'] = df['Values'].str.findall(r'(\d+) green')
df['green'] = df['green'].apply(lambda lst: list(map(int, lst)))

df

<>:1: SyntaxWarning: invalid escape sequence '\d'
<>:1: SyntaxWarning: invalid escape sequence '\d'
/var/folders/bs/zggx74yj4d721rnp57yp6h5r0000gn/T/ipykernel_14383/2464668597.py:1: SyntaxWarning: invalid escape sequence '\d'
  df['Game'] =df['Game'].str.replace('[^\d\.]','', regex=True).astype(int)

,Game,Values,Blue,red,green
0,1,"1 blue, 1 red; 10 red; 8 red, 1 blue, 1 green...","[1, 1, 5]","[1, 10, 8]","[1, 1]"
1,2,"9 green, 11 red; 1 green, 7 red, 1 blue; 1 re...","[1, 1, 1, 1]","[11, 7, 1, 3, 12, 7]","[9, 1, 1, 11, 5, 8]"
2,3,"16 blue, 2 red, 4 green; 8 red, 4 green; 7 gr...","[16, 16]","[2, 8]","[4, 4, 7]"
3,4,"3 green, 4 blue, 6 red; 7 red, 12 green, 5 bl...","[4, 5, 8]","[6, 7, 16]","[3, 12, 5]"
4,5,"4 green, 4 blue, 3 red; 4 green, 7 red, 1 blu...","[4, 1, 2, 4, 2]","[3, 7, 2, 7, 8]","[4, 4, 4, 3, 3]"
...,...,...,...,...,...
95,96,"5 red, 8 blue, 5 green; 12 blue, 2 red; 15 bl...","[8, 12, 15]","[5, 2, 2, 4]","[5, 1, 1]"
96,97,"5 red, 5 blue; 1 red, 11 blue; 3 green, 10 bl...","[5, 11, 10, 7, 2, 8]","[5, 1, 1, 6, 1]","[3, 3, 1]"
97,98,"4 red, 3 blue, 8 green; 5 blue, 2 red, 8 gree...","[3, 5, 2, 11, 6]","[4, 2, 10, 9, 11]","[8, 8, 7, 9, 10]"
98,99,"7 green, 3 red, 9 blue; 3 blue, 5 red, 4 gree...","[9, 3, 1, 12, 12]","[3, 5, 2, 1, 1]","[7, 4, 6, 1, 11]"
99,100,"2 blue, 1 red; 4 blue, 2 red, 1 green; 7 red,...","[2, 4, 5, 5]","[1, 2, 7, 2]","[1, 1]"

In [68]:
df['blueFLAG'] = df.Blue.explode().gt(14).groupby(level=0, sort=False).any()
df['redFLAG'] = df.red.explode().gt(12).groupby(level=0, sort=False).any()
df['greenFLAG'] = df.green.explode().gt(13).groupby(level=0, sort=False).any()

df["FLAG"] = df[['blueFLAG', 'redFLAG', 'greenFLAG']].any(axis='columns')
df

,Game,Values,Blue,red,green,blueFLAG,redFLAG,greenFLAG,FLAG
0,1,"1 blue, 1 red; 10 red; 8 red, 1 blue, 1 green...","[1, 1, 5]","[1, 10, 8]","[1, 1]",False,False,False,False
1,2,"9 green, 11 red; 1 green, 7 red, 1 blue; 1 re...","[1, 1, 1, 1]","[11, 7, 1, 3, 12, 7]","[9, 1, 1, 11, 5, 8]",False,False,False,False
2,3,"16 blue, 2 red, 4 green; 8 red, 4 green; 7 gr...","[16, 16]","[2, 8]","[4, 4, 7]",True,False,False,True
3,4,"3 green, 4 blue, 6 red; 7 red, 12 green, 5 bl...","[4, 5, 8]","[6, 7, 16]","[3, 12, 5]",False,True,False,True
4,5,"4 green, 4 blue, 3 red; 4 green, 7 red, 1 blu...","[4, 1, 2, 4, 2]","[3, 7, 2, 7, 8]","[4, 4, 4, 3, 3]",False,False,False,False
...,...,...,...,...,...,...,...,...,...
95,96,"5 red, 8 blue, 5 green; 12 blue, 2 red; 15 bl...","[8, 12, 15]","[5, 2, 2, 4]","[5, 1, 1]",True,False,False,True
96,97,"5 red, 5 blue; 1 red, 11 blue; 3 green, 10 bl...","[5, 11, 10, 7, 2, 8]","[5, 1, 1, 6, 1]","[3, 3, 1]",False,False,False,False
97,98,"4 red, 3 blue, 8 green; 5 blue, 2 red, 8 gree...","[3, 5, 2, 11, 6]","[4, 2, 10, 9, 11]","[8, 8, 7, 9, 10]",False,False,False,False
98,99,"7 green, 3 red, 9 blue; 3 blue, 5 red, 4 gree...","[9, 3, 1, 12, 12]","[3, 5, 2, 1, 1]","[7, 4, 6, 1, 11]",False,False,False,False
99,100,"2 blue, 1 red; 4 blue, 2 red, 1 green; 7 red,...","[2, 4, 5, 5]","[1, 2, 7, 2]","[1, 1]",False,False,False,False

In [69]:
filtered = df.loc[df['FLAG'] == False]
filtered

,Game,Values,Blue,red,green,blueFLAG,redFLAG,greenFLAG,FLAG
0,1,"1 blue, 1 red; 10 red; 8 red, 1 blue, 1 green...","[1, 1, 5]","[1, 10, 8]","[1, 1]",False,False,False,False
1,2,"9 green, 11 red; 1 green, 7 red, 1 blue; 1 re...","[1, 1, 1, 1]","[11, 7, 1, 3, 12, 7]","[9, 1, 1, 11, 5, 8]",False,False,False,False
4,5,"4 green, 4 blue, 3 red; 4 green, 7 red, 1 blu...","[4, 1, 2, 4, 2]","[3, 7, 2, 7, 8]","[4, 4, 4, 3, 3]",False,False,False,False
6,7,"2 green, 9 red, 9 blue; 12 red, 14 blue; 8 re...","[9, 14]","[9, 12, 8]","[2, 3]",False,False,False,False
8,9,"2 red, 1 blue, 10 green; 4 red, 1 blue, 5 gre...","[1, 1, 2]","[2, 4, 3, 8]","[10, 5, 6, 1]",False,False,False,False
9,10,"9 green; 6 red, 4 green, 4 blue; 9 red, 2 blu...","[4, 2, 8, 2, 7]","[6, 9, 9, 4]","[9, 4, 9, 12, 8, 6]",False,False,False,False
11,12,"6 blue, 9 red, 4 green; 1 green, 8 blue; 4 gr...","[6, 8, 8, 7]","[9, 1, 2]","[4, 1, 4, 7]",False,False,False,False
13,14,"1 red, 4 blue, 3 green; 2 red, 1 green, 1 blu...","[4, 1, 1, 4]","[1, 2, 1, 3]","[3, 1, 5, 4]",False,False,False,False
16,17,"4 red, 1 green, 1 blue; 1 green, 1 red, 11 bl...","[1, 11, 7]","[4, 1, 1]","[1, 1]",False,False,False,False
19,20,"8 green, 3 blue, 3 red; 5 green, 6 red, 1 blu...","[3, 1, 1, 1, 1]","[3, 6, 6, 4, 4]","[8, 5, 13, 4]",False,False,False,False
22,23,"4 red, 3 blue; 2 green, 7 red, 6 blue; 1 gree...","[3, 6, 3]","[4, 7, 2]","[2, 1]",False,False,False,False
23,24,"7 red, 3 green, 2 blue; 3 red, 9 green, 9 blu...","[2, 9, 7]","[7, 3, 6]","[3, 9, 8]",False,False,False,False
24,25,"2 red, 2 green, 2 blue; 3 green, 1 red, 4 blu...","[2, 4, 3, 1, 2]","[2, 1, 4, 5, 4, 3]","[2, 3, 4, 2, 5]",False,False,False,False
28,29,"7 green, 10 red; 9 green, 2 red, 1 blue; 3 bl...","[1, 3]","[10, 2, 5]","[7, 9, 13]",False,False,False,False
31,32,"6 red, 3 green, 7 blue; 3 green, 7 blue, 3 re...","[7, 7, 7, 7]","[6, 3, 1, 5, 11]","[3, 3, 4, 6, 9]",False,False,False,False
34,35,"6 blue, 4 green, 7 red; 2 blue, 6 red; 4 gree...","[6, 2, 2, 1, 10, 11]","[7, 6, 11, 2, 10]","[4, 4, 4, 1, 4]",False,False,False,False
35,36,"13 blue, 6 green, 7 red; 5 red, 9 blue, 9 gre...","[13, 9, 2, 2, 5, 12]","[7, 5, 6, 7, 7]","[6, 9, 3, 7, 3]",False,False,False,False
36,37,"2 red, 12 green, 3 blue; 6 red, 4 blue; 3 blu...","[3, 4, 3, 5]","[2, 6, 4]","[12, 1, 6]",False,False,False,False
39,40,"1 red, 2 green, 3 blue; 6 blue, 5 green, 1 re...","[3, 6, 1]","[1, 1]","[2, 5, 5]",False,False,False,False
44,45,"6 blue; 6 green, 6 blue, 1 red; 5 blue, 11 gr...","[6, 6, 5, 6]",[1],"[6, 11, 4]",False,False,False,False
45,46,"6 green, 3 blue, 2 red; 9 green, 4 red, 2 blu...","[3, 2, 3]","[2, 4, 1]","[6, 9, 9]",False,False,False,False
46,47,"6 red, 3 blue, 9 green; 3 green, 11 blue; 4 b...","[3, 11, 4, 11]","[6, 1]","[9, 3, 11]",False,False,False,False
48,49,"8 green, 4 red; 1 red, 6 blue; 5 blue, 8 gree...","[6, 5, 3, 5]","[4, 1, 1, 2]","[8, 8, 2, 5]",False,False,False,False
49,50,"1 red, 8 green, 3 blue; 1 blue, 9 green; 3 gr...","[3, 1, 6]",[1],"[8, 9, 3]",False,False,False,False
50,51,"8 green, 8 red, 8 blue; 9 green, 2 red, 6 blu...","[8, 6, 1, 5, 7]","[8, 2, 1, 1, 5]","[8, 9, 1, 7, 5]",False,False,False,False
51,52,"2 green, 1 red; 4 blue, 7 red, 2 green; 3 red...","[4, 4, 1, 8, 4]","[1, 7, 3, 7, 8, 4]","[2, 2, 1, 1, 3]",False,False,False,False
52,53,"9 blue, 9 red; 3 blue, 3 green, 5 red; 1 gree...","[9, 3, 6, 3]","[9, 5, 2, 4]","[3, 1, 3]",False,False,False,False
53,54,"1 blue, 2 red, 2 green; 6 green, 1 blue, 3 re...","[1, 1, 1]","[2, 3]","[2, 6, 1]",False,False,False,False
57,58,"1 green, 9 red, 11 blue; 5 green, 11 red, 6 b...","[11, 6, 8, 14, 9]","[9, 11, 3, 4, 1]","[1, 5, 2, 2]",False,False,False,False
61,62,"10 blue, 2 green, 7 red; 2 red, 2 green, 10 b...","[10, 10]","[7, 2, 5]","[2, 2]",False,False,False,False
63,64,"11 red, 3 green; 3 red, 1 blue, 3 green; 2 gr...","[1, 4, 4, 2]","[11, 3, 2, 9, 7, 9]","[3, 3, 2, 1, 3, 3]",False,False,False,False
64,65,"2 red, 12 green; 3 red, 3 green; 8 green, 1 b...",[1],"[2, 3, 4, 2]","[12, 3, 8, 3]",False,False,False,False
66,67,"6 red, 1 green; 1 green, 1 blue, 12 red; 11 r...","[1, 2]","[6, 12, 11]","[1, 1]",False,False,False,False
67,68,"4 green, 5 red; 9 blue, 1 red; 1 green, 2 red...","[9, 7, 8, 2]","[5, 1, 2, 6, 7]","[4, 1, 5, 2]",False,False,False,False
69,70,"7 red, 5 blue, 4 green; 6 red, 12 blue, 13 gr...","[5, 12, 8, 9]","[7, 6, 4, 2]","[4, 13, 5, 5]",False,False,False,False
72,73,"1 green, 7 red; 6 red, 2 blue; 5 red, 9 blue;...","[2, 9, 12]","[7, 6, 5, 9]",[1],False,False,False,False
78,79,"3 red, 10 green, 10 blue; 10 blue, 12 green; ...","[10, 10, 10]","[3, 3]","[10, 12, 7]",False,False,False,False
80,81,"1 green, 3 red, 6 blue; 5 blue, 1 red, 1 gree...","[6, 5, 6]","[3, 1, 9]","[1, 1]",False,False,False,False
83,84,"3 red, 3 blue, 2 green; 3 red, 9 green; 2 blu...","[3, 2, 1]","[3, 3, 1, 1]","[2, 9, 11, 11]",False,False,False,False
85,86,"11 red, 4 green; 2 green, 1 blue, 10 red; 11 ...","[1, 3]","[11, 10, 11]","[4, 2, 9]",False,False,False,False
87,88,"1 red, 12 green; 4 green, 3 blue; 6 blue, 12 ...","[3, 6, 2]","[1, 1]","[12, 4, 12]",False,False,False,False
89,90,"2 red, 2 blue, 7 green; 7 green, 2 red, 12 bl...","[2, 12, 5]","[2, 2, 6]","[7, 7, 9]",False,False,False,False
90,91,"14 blue, 2 red, 7 green; 7 blue, 7 green; 1 r...","[14, 7, 10, 7, 13]","[2, 1, 4, 1, 1]","[7, 7, 5, 4, 5, 5]",False,False,False,False
93,94,"4 green, 9 blue; 2 green, 6 red, 3 blue; 5 re...","[9, 3, 8, 6, 6]","[6, 5, 5, 7]","[4, 2, 4, 4, 7]",False,False,False,False
96,97,"5 red, 5 blue; 1 red, 11 blue; 3 green, 10 bl...","[5, 11, 10, 7, 2, 8]","[5, 1, 1, 6, 1]","[3, 3, 1]",False,False,False,False
97,98,"4 red, 3 blue, 8 green; 5 blue, 2 red, 8 gree...","[3, 5, 2, 11, 6]","[4, 2, 10, 9, 11]","[8, 8, 7, 9, 10]",False,False,False,False
98,99,"7 green, 3 red, 9 blue; 3 blue, 5 red, 4 gree...","[9, 3, 1, 12, 12]","[3, 5, 2, 1, 1]","[7, 4, 6, 1, 11]",False,False,False,False
99,100,"2 blue, 1 red; 4 blue, 2 red, 1 green; 7 red,...","[2, 4, 5, 5]","[1, 2, 7, 2]","[1, 1]",False,False,False,False

In [70]:
sum(filtered['Game'])

2439

In [79]:
df['bluemax'] = df['Blue'].apply(lambda x: max(x))
df['redmax'] = df['red'].apply(lambda x: max(x))
df['greenmax'] = df['green'].apply(lambda x: max(x))
df['power'] = df['bluemax']*df['redmax']*df['greenmax']
print(sum(df['power']))

63711